import type { BehaviorMatch, PropertyMatch, ScannedType } from "../language-scanner.js";

/*
 * Extraction from one Java source file, the C# scanner's approach with two
 * differences: comments and string literals are blanked out before anything
 * is matched, so braces inside them never count, and an annotation must sit
 * directly on the declaration (annotations and modifiers only in between)
 * rather than anywhere before it.
 *
 * Behaviors are the methods that are not private — in Java the default,
 * package-private visibility is how a domain package exposes logic to itself.
 * Properties are the instance fields and record components, whatever their
 * visibility: a block's data is its data whether a getter is written by hand,
 * generated by Lombok (@Value, @Data, @Getter) or absent. That is what makes
 * Lombok irrelevant here — nothing it generates is read, nothing it hides is
 * missed.
 */

/**
 * The stereotype annotations of the Noesis Java annotations module
 * (`vision.noesis.annotations`), by simple name, with the building block type
 * each one declares in the model's vocabulary.
 */
export const STEREOTYPE_ANNOTATIONS: Readonly<Record<string, string>> = {
  AggregateRoot: "Aggregate",
  Entity: "Entity",
  ValueObject: "ValueObject",
  Identifier: "Identifier",
  DomainService: "DomainService",
  ApplicationService: "ApplicationService",
  Repository: "Repository",
  Factory: "Factory",
  Port: "Port",
  Adapter: "Adapter",
  Command: "Command",
  Query: "Query",
  Event: "DomainEvent",
};

type TypeKind = "class" | "interface" | "enum" | "record";

const PACKAGE_PATTERN = /^[ \t]*package[ \t]+([\w.]+)[ \t]*;/m;

const ANNOTATION = String.raw`@[\w.]+(?:\s*\((?:[^()]|\([^()]*\))*\))?`;
const MODIFIER = String.raw`(?:public|protected|private|abstract|final|static|sealed|non-sealed|strictfp)\b`;
// Annotations and modifiers, then the kind keyword and the name. The keyword must not
// follow `@` (an `@interface` declares an annotation type) or `.` (`Order.class`).
const TYPE_DECLARATION_PATTERN = new RegExp(
  String.raw`((?:(?:${ANNOTATION}|${MODIFIER})\s+)*)(?<![@.\w])(class|interface|enum|record)\s+(\w+)`,
  "g"
);
const ANNOTATION_NAME_PATTERN = /@([\w.]+)/g;
const ANNOTATION_PATTERN = new RegExp(ANNOTATION, "g");

const DISQUALIFYING_METHOD_KEYWORDS = /\b(class|interface|enum|record|new|return|throw)\b/;
const DISQUALIFYING_FIELD_KEYWORDS =
  /\b(class|interface|enum|record|new|return|throw|import|package)\b/;
const MODIFIER_WORD_PATTERN =
  /\b(?:public|protected|private|abstract|final|static|default|synchronized|native|strictfp|sealed|non-sealed|transient|volatile)\b/g;
const TECHNICAL_METHOD_NAMES = new Set(["equals", "hashCode", "toString"]);

export function extractPackage(content: string): string | null {
  return PACKAGE_PATTERN.exec(blankOut(content))?.[1] ?? null;
}

/** Every type in the file that carries a stereotype annotation, with its behaviors and properties. */
export function parseStereotypedTypes(content: string): ScannedType[] {
  const text = blankOut(content);
  const types: ScannedType[] = [];
  for (const match of text.matchAll(TYPE_DECLARATION_PATTERN)) {
    const [, prefix = "", kind = "", typeName = ""] = match;
    const blockType = stereotypeOf(annotationNames(prefix));
    if (blockType === null) continue;
    const declarationEnd = match.index + match[0].length;
    const members = extractMembers(text, declarationEnd, typeName, kind as TypeKind);
    types.push({ typeName, blockType, nameOverride: null, ...members });
  }
  return types;
}

/** The block type the annotations declare, or null when none is a stereotype. */
export function stereotypeOf(annotations: string[]): string | null {
  for (const annotation of annotations) {
    const blockType = STEREOTYPE_ANNOTATIONS[annotation];
    if (blockType !== undefined) return blockType;
  }
  return null;
}

/** Comments and string/char literals replaced by spaces, newlines kept, so nothing inside them is matched. */
export function blankOut(content: string): string {
  let out = "";
  let i = 0;
  const blank = (end: number) => {
    for (let j = i; j < end; j++) out += content[j] === "\n" ? "\n" : " ";
    i = end;
  };
  while (i < content.length) {
    const two = content.slice(i, i + 2);
    if (two === "//") {
      const end = content.indexOf("\n", i);
      blank(end === -1 ? content.length : end);
    } else if (two === "/*") {
      const end = content.indexOf("*/", i + 2);
      blank(end === -1 ? content.length : end + 2);
    } else if (content.startsWith('"""', i)) {
      const end = content.indexOf('"""', i + 3);
      blank(end === -1 ? content.length : end + 3);
    } else if (content[i] === '"' || content[i] === "'") {
      blank(literalEnd(content, i));
    } else {
      out += content[i];
      i++;
    }
  }
  return out;
}

function annotationNames(prefix: string): string[] {
  return [...prefix.matchAll(ANNOTATION_NAME_PATTERN)].map((match) => {
    const qualified = match[1] ?? "";
    return qualified.slice(qualified.lastIndexOf(".") + 1);
  });
}

interface Members {
  behaviors: BehaviorMatch[];
  properties: PropertyMatch[];
}

/**
 * The behaviors and properties of the type whose declaration ends at
 * `searchStart`: a record's components from its header, then the members
 * declared directly in the body. Enums contribute nothing: their constants
 * dominate the body and their methods are rarely domain ones.
 */
function extractMembers(
  text: string,
  searchStart: number,
  typeName: string,
  kind: TypeKind
): Members {
  const none: Members = { behaviors: [], properties: [] };
  if (kind === "enum") return none;
  const bodyStart = findTypeBodyStart(text, searchStart);
  if (bodyStart === -1) return none;
  const bodyEnd = findMatchingBrace(text, bodyStart);
  if (bodyEnd === -1) return none;

  const properties =
    kind === "record" ? recordComponents(text.substring(searchStart, bodyStart)) : [];
  const behaviors: BehaviorMatch[] = [];
  const seenMethods = new Set<string>();
  for (const statement of flattenBraceBlocks(text.substring(bodyStart + 1, bodyEnd)).split(";")) {
    const method = parseMethodStatement(statement, typeName);
    if (method !== null) {
      if (!seenMethods.has(method.methodName)) {
        seenMethods.add(method.methodName);
        behaviors.push(method);
      }
      continue;
    }
    // Interface fields are constants; a record's data is its header.
    if (kind === "interface" || kind === "record") continue;
    properties.push(...parseFieldStatement(statement));
  }
  return { behaviors, properties };
}

/** The `{` opening the body: the first brace outside parentheses, which a record header has. */
function findTypeBodyStart(text: string, from: number): number {
  let parens = 0;
  for (let i = from; i < text.length; i++) {
    const ch = text[i];
    if (ch === "(") parens++;
    else if (ch === ")") parens--;
    else if (ch === "{" && parens === 0) return i;
    else if (ch === ";" && parens === 0) return -1;
  }
  return -1;
}

function findMatchingBrace(text: string, start: number): number {
  let depth = 0;
  for (let i = start; i < text.length; i++) {
    if (text[i] === "{") depth++;
    else if (text[i] === "}" && --depth === 0) return i;
  }
  return -1;
}

/** The components of a record header `(Type name, Type name)`, annotations dropped. */
function recordComponents(header: string): PropertyMatch[] {
  const open = header.indexOf("(");
  if (open === -1) return [];
  const close = matchingParen(header, open);
  if (close === -1) return [];
  const inside = header.substring(open + 1, close).replace(ANNOTATION_PATTERN, " ");
  return splitTopLevel(inside, ",")
    .map((component) => declarator(component))
    .filter((c): c is PropertyMatch => c !== null);
}

function matchingParen(text: string, open: number): number {
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")" && --depth === 0) return i;
  }
  return -1;
}

/**
 * Reads one statement as a field declaration: modifiers, a type and one or
 * more names, with or without an initialiser. Static fields are constants
 * and configuration, not the block's data.
 */
function parseFieldStatement(statement: string): PropertyMatch[] {
  const withoutAnnotations = statement.replace(ANNOTATION_PATTERN, " ");
  const equals = withoutAnnotations.indexOf("=");
  const declaration = equals === -1 ? withoutAnnotations : withoutAnnotations.substring(0, equals);
  if (declaration.includes("(") || DISQUALIFYING_FIELD_KEYWORDS.test(declaration)) return [];
  const modifiers: string[] = declaration.match(MODIFIER_WORD_PATTERN) ?? [];
  if (modifiers.includes("static")) return [];
  const withoutModifiers = declaration.replace(MODIFIER_WORD_PATTERN, " ");

  const [first, ...more] = splitTopLevel(withoutModifiers, ",");
  const head = declarator(first ?? "");
  if (head === null) return [];
  // `int a, b;` declares two fields of one type.
  const siblings = more
    .map((name) => name.trim().replace(/\[\s*]/g, ""))
    .filter((name) => /^\w+$/.test(name));
  return [head, ...siblings.map((name) => ({ name, type: head.type }))];
}

/** `Type name` — the last word is the name, everything before it the type; null when there is no type. */
function declarator(text: string): PropertyMatch | null {
  const trimmed = text.trim().replace(/\[\s*]$/, "");
  const name = trailingWord(trimmed);
  const type = trimmed
    .slice(0, trimmed.length - name.length)
    .trim()
    .replace(/\s+/g, " ");
  if (name === "" || type === "" || !/^\w+$/.test(name)) return null;
  return { name, type };
}

/** Split on a separator outside `<…>` and `(…)`. */
function splitTopLevel(text: string, separator: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch === "<" || ch === "(") depth++;
    else if (ch === ">" || ch === ")") depth--;
    else if (ch === separator && depth === 0) {
      parts.push(text.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(text.slice(start));
  return parts;
}

/** Nested blocks (method bodies, nested types, initialisers) collapsed to a statement end. */
function flattenBraceBlocks(content: string): string {
  let result = "";
  let depth = 0;
  for (const ch of content) {
    if (ch === "{") {
      if (depth === 0) result += ";";
      depth++;
    } else if (ch === "}") {
      if (depth > 0) depth--;
    } else if (depth === 0) {
      result += ch;
    }
  }
  return result;
}

/**
 * Reads one statement as a method header. Any method that is not private is
 * a behavior — package-private included, since that is how a Java domain
 * package exposes logic to itself. Constructors, the Object trio and
 * anything with an initialiser (a field) or a statement keyword are not
 * methods.
 */
function parseMethodStatement(statement: string, typeName: string): BehaviorMatch | null {
  const withoutAnnotations = statement.replace(ANNOTATION_PATTERN, " ");
  if (DISQUALIFYING_METHOD_KEYWORDS.test(withoutAnnotations)) return null;

  const parenIdx = withoutAnnotations.indexOf("(");
  if (parenIdx === -1) return null;
  const header = withoutAnnotations.substring(0, parenIdx);
  if (header.includes("=")) return null;

  const modifiers: string[] = header.match(MODIFIER_WORD_PATTERN) ?? [];
  if (modifiers.includes("private")) return null;

  const methodName = trailingWord(header.trimEnd());
  if (methodName === "") return null;
  if (methodName === typeName || TECHNICAL_METHOD_NAMES.has(methodName)) return null;
  // Only a name and no return type: not a method header.
  if (header.replace(MODIFIER_WORD_PATTERN, "").trim() === methodName) return null;

  return { methodName, nameOverride: null, actor: null };
}

function trailingWord(text: string): string {
  let start = text.length;
  while (start > 0 && /\w/.test(text[start - 1] ?? "")) start--;
  return text.slice(start);
}

function literalEnd(content: string, open: number): number {
  const quote = content[open];
  for (let i = open + 1; i < content.length; i++) {
    if (content[i] === "\\") i++;
    else if (content[i] === quote || content[i] === "\n") return i + 1;
  }
  return content.length;
}
